NXBT-3523: Fix Skaffold build - use recent API version
nuxeo/nuxeo-explorer pull request #137
Opened 2021-07-20 15:11 UTC by ataillefer

Following Skaffold uprade to 1.27.0 on base builder.

Also, fix kaniko build intermittent issue, due to a memory limitation in the kaniko pod while snapshotting the filesystem.
Solved by:
  - Setting CPU/memory resource requests/limits for the kaniko executor container.
  - Allowing to bind the kaniko pod to the Platform dedicated node pool, using tolerations.
  - Using the kaniko optimization options for filesystem snapshotting (skaffold version upgrade required).

2021-07-20 15:11 UTC, nuxeojenkins commented
View issue in JIRA: [NXBT-3523](https://jira.nuxeo.com/browse/NXBT-3523): Upgrade the skaffold version on jx-platform-builders

2021-07-20 15:24 UTC, kevinleturc approved these changes

2021-07-20 16:43 UTC, atchertchian requested changes
Thanks! The job at https://jenkins.platform.dev.nuxeo.com/job/explorer/job/export-platform-explorer-reference/53/ validated the change for the "reference export" docker image build :+1: 

As discussed, and as the PR checks should show, the same change is needed for the "simple" explorer docker image (see failure on master at https://jenkins.platform.dev.nuxeo.com/job/explorer/job/nuxeo-explorer/job/master/62/).

Thanks again!

2021-07-21 08:11 UTC, atchertchian submitted a review, later dismissed

2021-07-21 09:19 UTC, kevinleturc submitted a review, later dismissed

2021-07-22 06:37 UTC, atchertchian approved these changes

2021-07-22 09:20 UTC, kevinleturc approved these changes

2021-07-22 09:30 UTC, merged