NXP-29708 improve rest response for automation + review transaction rollbacks
nuxeo/nuxeo-explorer pull request #85
Opened 2020-11-25 17:58 UTC by atchertchian

2020-11-25 17:58 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29708](https://jira.nuxeo.com/browse/NXP-29708): Better handle rest errors on explorer upload API

2020-11-25 18:12 UTC, efge requested changes
Mostly details

2020-11-25 18:12 UTC, efge commented on modules/nuxeo-apidoc-webengine/src/main/java/org/nuxeo/apidoc/browse/Distribution.java
> +                           .entity("Upload not done:" + e.getMessage())
Add a space after `:`

2020-11-25 18:12 UTC, efge commented on modules/nuxeo-apidoc-core/src/main/java/org/nuxeo/apidoc/snapshot/SnapshotManagerComponent.java
> +    protected static final int UPLOAD_SAVE_INTERVAL = 3000;
Can you add `// save every 3000 documents` to clarify that it's a number of docs and not an interval in seconds or something else

2020-11-25 18:12 UTC, efge commented on modules/nuxeo-apidoc-webengine/src/main/java/org/nuxeo/apidoc/browse/Distribution.java
> +        if (TransactionHelper.isTransactionActiveOrMarkedRollback()) {
The `if` shouldn't be needed, the caller should always know that it's in a transactional context. (This is a general issue in too much of our code, the no-transaction should be extremely rare and known to the context.)

2020-11-25 18:12 UTC, efge commented on ci/Jenkinsfiles/export.groovy
> +                  ${curlCommand} -d 'name=${params.SNAPSHOT_NAME}' -d 'version=${NUXEO_IMAGE_VERSION}' -H"Accept: text/plain" ${explorerUrl}/save
Add a space after `-H` for consistency

2020-11-25 18:12 UTC, efge commented on modules/nuxeo-apidoc-webengine/src/main/java/org/nuxeo/apidoc/browse/Distribution.java
> +
Remove extra empty line

2020-11-25 18:12 UTC, efge commented on modules/nuxeo-apidoc-webengine/src/main/java/org/nuxeo/apidoc/browse/Distribution.java
> +                               .entity("Save failed:" + errorMessage)
Add space after `:`

2020-11-27 13:20 UTC, kevinleturc approved these changes

2020-12-01 12:56 UTC, merged