NXP-30169: add rest api to get the list of packages in json
nuxeo/nuxeo-explorer pull request #97
Opened 2021-02-18 08:38 UTC by atchertchian

2021-02-18 08:38 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-30169](https://jira.nuxeo.com/browse/NXP-30169): Get the list of explorer packages in json

2021-02-18 08:44 UTC, kevinleturc submitted a review, later dismissed

2021-02-18 09:18 UTC, atchertchian commented
force pushed to add missing maven dep to nuxeo-java-client

2021-02-18 12:00 UTC, efge requested changes

2021-02-18 12:00 UTC, efge commented on modules/nuxeo-apidoc-webengine/src/main/java/org/nuxeo/apidoc/browse/ApiBrowser.java
> +     * Returns a simple json export of packages names.
Please document the format using a short example JSON export in the Javadoc.

2021-02-19 13:18 UTC, efge approved these changes

2021-02-19 16:55 UTC, merged